language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: xj4muhj2gXFkI3RcKKdMmL/nyOUjh+vCA6d1C32d2erkmKkm3t89lqwlCl7v2uD1BbcyURaFv8yGBUqTcmjTc7smxqU0k+ZSmHn5rKSitZ1RnUrz1n5f9cw9fMfi7k1xe40MU65MKjj750mw3Aj3XcYNyqvslA7k6Nhed1vAvKtcXCt2qVIdx1sxH4fyPoZLDixPsWBa/bpP0ZeiNe7Dm8T9asaG1EsXBJ4XsTdwMHXofEgsht8483xYKr5Hy2CPKcDlgMZbnx5LrJ/XRDVzw0yKBrb++vtm9ln6HFOqk0b0D0DlEwZt7GbhOQRfB8i5bgskZ/muWbUkavie6RtY/23+kLYJejsFjUoUowuW5bWwOBdseMVb9bD6o53nZxZDA9f6InAAii8jprYMXKSKP2vIHBs7euLnv0nTtXkvkft3emk3iXZjcCNkudMsWvnJ6i8KJv5X612ygzFYOtiZwh9qpMGHft0lWnclHG425RljLk2v3OWlG9pbp2aWBCDfyaJygqzEG6KV8WLGWs9U8aA66vYvo/d2S8np+7DhT6hO34PWT04Ayu9+VjaAIvNfGWNS0ftQqKXI4o61Mecx/gjKBqt9i9D6y0LRkQDHv2M/pYf6IdL5msW3JXXLGQ3uS6xW9V9GRygn9+GieIwDPlfDn/Lx1rxg2GVpDRrgL/c=
  app: medicine-cabinet
  on:
    repo: miamiyankee13/medicine-cabinet
